### ISSUE TITLE
How to adjust models?

### ISSUE THREAD

**Issue by nbenezri** [fivetran/dbt_stripe#43] opened 2022-09-13 13:17 UTC
After changing the metadata variables I saw not all columns are showing in the destination transformation schema. So I went and edit them myself in dbt_packages/stripe/models. however it did not do anything, not even with `--full-refresh`. I guess this is somewhat related to `dbt_packages` being in `.gitignore`. 
Am I allowed to change it? if I change it - will it work?

I don't want to break stuff.

The changes I've done to the dbt_project.yml are:
+  stripe__charge_metadata: ['extras', 'product', 'userid'] 
+  stripe__invoice_metadata: ['extras', 'product', 'userid'] 
+  stripe__subscription_metadata: ['extras', 'userid'] 
+  stripe__customer_metadata: ['userid']

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-13 13:47
Hi @nbenezri would you be able to share a snippet of your variables in your root dbt_project.

Defining the variables the way you have shown above should work. I would be curious if maybe there is an error with how the variables are defined within your project.

**Comment by nbenezri** [comment] 2022-09-13 13:58
```
[nir@dba-dev fivetran_dbt]$ cat dbt_project.yml 

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'fivetran_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fivetran_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  fivetran_dbt:
  zendesk:
    intermediate:
    sla_policy:
    ticket_history:
  zendesk_source:
  jira:  
  jira_source:
  stripe:
  stripe_source:
  
vars:
  using_schedules: False
  jira_database: dkall
  jira_schema: jira
  #jira:
  #  issue_field_history_columns: ['the', 'list', 'of', 'field', 'names']
  stripe_source:
    stripe_database: dkall
    stripe_schema: stripe
  stripe_database: dkall
  stripe_schema: stripe
  stripe__subscription_history: True
  stripe_source:
    using_invoice_line_sub_filter: false
  stripe__charge_metadata: ['extras', 'product', 'userid'] # Note: this is case-SENSITIVE and must match the casing of the property as it appears in the JSON
  stripe__invoice_metadata: ['extras', 'product', 'userid'] 
  #stripe__payment_intent_metadata: ['the', 'list', 'of', 'property', 'fields'] 
  #stripe__payment_method_metadata: ['the', 'list', 'of', 'property', 'fields'] 
  #stripe__payout_metadata: ['the', 'list', 'of', 'property', 'fields'] 
  #stripe__plan_metadata: ['the', 'list', 'of', 'property', 'fields'] 
  #stripe__refund_metadata: ['the', 'list', 'of', 'property', 'fields'] 
  stripe__subscription_metadata: ['extras', 'userid'] 
  stripe__customer_metadata: ['userid'] 
  zendesk_source:
    zendesk_database: dkall
    zendesk_schema: zendesk
  zendesk:
    ticket_field_history_timeframe_years: 1
```

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-13 14:06
Thanks so much for sharing these details @nbenezri. The declaration of these variables seems accurate 🤔 

I am especially curious since you mentioned the `stripe__customer_metadata: ['userid'] ` works as intended. Are you able to confirm that for the other metadata variables that the fields are included in the JSON object within the source?

**Comment by nbenezri** [comment] 2022-09-13 14:11
They are. and they are appearing in the staging schema.

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-14 14:45
Hi @nbenezri if you wanted to fork the repo and make your changes directly in your own fork, you can then install your fork (with your custom changes) instead of our package. You would use the following syntax in your `packages.yml` to install your forked version of the package.
```yml
packages:
  - git: https://github.com/nbenezri/dbt_stripe.git
    revision: custom-branch
    warn-unpinned: false
```

This way you can make whatever changes you want directly in your own codebase and it will still be installed as a package. This will allow you to circumvent the need for disabling and copy/pasting which can result in a bunch of headache and compilation errors as dbt has a bunch of rules with disabling and having models with the same name.

You make a great point though that it would be helpful for us to possibly put together a guide for customers on how to fork or edit package code if needed.

**Comment by nbenezri** [comment] 2022-09-15 09:37
Work like a charm! thanks! 
If you want I can share the dbt modifications I did.

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-15 13:33
Brilliant! Yeah if you wanted to share your fork I would be happy to take a look. 

We have also had a few individuals in the past open PRs from their forks to contribute the code back into the package. I can look through your updates and if they make sense for the larger user base, we can work to incorporate it!

**Comment by nbenezri** [comment] 2022-09-15 16:51
[Archive.zip](https://github.com/fivetran/dbt_stripe/files/9577377/Archive.zip)

Repo is private - can't share it. But here are the files.

**Comment by nbenezri** [comment] 2022-09-15 16:52
BTW I know this is not your field anymore, but I push this change into master and the schedule in fivetran transformation is acting up.
Getting:

```
Execution Failure. dbt packages failed to install. The 'dbt deps' command had the following execution result: 
Command exit code: 2
stderr: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/git.py", line 65, in clone
    result = run_cmd(cwd, clone_cmd, env={"LC_ALL": "C"})
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/system.py", line 435, in run_cmd
    raise dbt.exceptions.CommandResultError(cwd, cmd, proc.returncode, out, err)
dbt.exceptions.CommandResultError: Got a non-zero returncode running: ['/usr/bin/git', 'clone', '--depth', '1', 'git@bitbucket.org:distrokid/fivetran-dbt-stripe.git', '66682aa22add127acad34de7b8f7fbf5']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/main.py", line 129, in main
    results, succeeded = handle_and_check(args)
  File "/usr/local/lib/python3.8/dist-packages/dbt/main.py", line 192, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/lib/python3.8/dist-packages/dbt/main.py", line 239, in run_from_args
    results = task.run()
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/deps.py", line 56, in run
    final_deps = resolve_packages(packages, self.config)
  File "/usr/local/lib/python3.8/dist-packages/dbt/deps/resolver.py", line 131, in resolve_packages
    target = final[package].resolved().fetch_metadata(config, renderer)
  File "/usr/local/lib/python3.8/dist-packages/dbt/deps/base.py", line 86, in fetch_metadata
    self._cached_metadata = self._fetch_metadata(project, renderer)
  File "/usr/local/lib/python3.8/dist-packages/dbt/deps/git.py", line 93, in _fetch_metadata
    path = self._checkout()
  File "/usr/local/lib/python3.8/dist-packages/dbt/deps/git.py", line 79, in _checkout
    dir_ = git.clone_and_checkout(
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/git.py", line 137, in clone_and_checkout
    _, err = clone(
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/git.py", line 67, in clone
    _raise_git_cloning_error(repo, revision, exc)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/git.py", line 37, in _raise_git_cloning_error
    bad_package_spec(repo, revision, stderr)
  File "/usr/local/lib/python3.8/dist-packages/dbt/exceptions.py", line 735, in bad_package_spec
    raise InternalException(scrub_secrets(msg, env_secrets()))
dbt.exceptions.InternalException: Error checking out spec='None' for repo git@bitbucket.org:distrokid/fivetran-dbt-stripe.git
Cloning into '66682aa22add127acad34de7b8f7fbf5'...
fatal: unable to fork
stdout: 
16:27:41  Running with dbt=1.2.0
16:27:42  Encountered an error:
Error checking out spec='None' for repo git@bitbucket.org:distrokid/fivetran-dbt-stripe.git
Cloning into '66682aa22add127acad34de7b8f7fbf5'...
fatal: unable to fork
```

If you have any idea why it unable to fork it...

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-15 17:53
Hey @nbenezri no worries at all. Hopefully I can help.

What are the contents of your `packages.yml` file?

**Comment by nbenezri** [comment] 2022-09-16 07:16
```
packages:
  - package: fivetran/zendesk_source
    version: [">=0.7.0", "<0.8.0"]
  - package: fivetran/zendesk
    version: [">=0.9.0", "<0.10.0"]
  - package: fivetran/jira_source
    version: [">=0.4.0", "<0.5.0"]
  - package: fivetran/jira
    version: [">=0.8.0", "<0.9.0"]
  - package: fivetran/stripe_source
    version: [">=0.7.0", "<0.8.0"]
  - git: git@bitbucket.org:distrokid/fivetran-dbt-stripe.git
    revision: main
    warn-unpinned: false
```

It should work as both repo's (`fivetran-dbt-stripe`, and this one) in the same master repo. So the ssh key should work for both (it works for this one).
If I change to https it request user/pass.

**Comment by nbenezri** [comment] 2022-09-20 15:23
Would love some help

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-20 15:33
@nbenezri do the package installs on `dbt deps` work locally? Is the only issue when deploying it, or does it fail locally as well?

**Comment by nbenezri** [comment] 2022-09-20 16:26
Locally it works. Actually, until the issue is solved, I use crontab from my server instead of Fivetran's transformation schedule.

**Comment by fivetran-joemarkiewicz** [comment] 2022-09-20 17:08
Since it works locally, I imagine this is something that needs to be addressed at the Fivetran Transformations layer. Unfortunately, I am not part of this team but I would recommend opening a [Support Ticket](https://support.fivetran.com/hc/en-us) (if you have not already) to help resolve this issue.

I apologize I am unable to help address this, but I do believe it has something to do with how Fivetran Transformations talks to other repos.

**Comment by fivetran-reneeli** [comment] 2023-01-31 21:46
Closing this issue out as we have now introduced the [ability to bring metadata fields](https://github.com/fivetran/dbt_stripe/blob/main/README.md#pivoting-out-metadata-properties) into select staging models!

**Closed by fivetran-reneeli** 2023-01-31 21:46 UTC
